DROP TABLE IF EXISTS intervention;

CREATE TABLE intervention (
       "schema_name" VARCHAR(50) NOT NULL,
       intervention_id INTEGER NOT NULL,
       created TIMESTAMP WITH TIME ZONE,
       modified TIMESTAMP WITH TIME ZONE,
       document_type VARCHAR(255),
       "number" VARCHAR(64),
       title VARCHAR(256),
       status VARCHAR(32),
       "start" DATE,
       "end" DATE,
       submission_date DATE,
       submission_date_prc DATE,
       review_date_prc DATE,
       prc_review_document VARCHAR(1024),
       signed_by_unicef_date DATE,
       signed_by_partner_date DATE,
       population_focus VARCHAR(130),
       agreement_id INTEGER,
       partner_authorized_officer_signatory_id INTEGER,
       unicef_signatory_id INTEGER,
       signed_pd_document VARCHAR(1024),
       country_programme_id INTEGER,
       contingency_pd BOOLEAN,
       metadata JSONB,
       unicef_signatory_first_name VARCHAR(30),
       unicef_signatory_last_name VARCHAR(30),
       unicef_signatory_email  VARCHAR(254),
       partner_signatory_title VARCHAR(64),
       partner_signatory_first_name VARCHAR(64),
       partner_signatory_last_name VARCHAR(64),
       partner_signatory_email VARCHAR(128),
       partner_signatory_phone VARCHAR(64),
       unicef_focal_point_first_name VARCHAR(30),
       unicef_focal_point_last_name VARCHAR(30),
       unicef_focal_point_email VARCHAR(254),
       partner_focal_point_title VARCHAR(64),
       partner_focal_point_first_name VARCHAR(64),
       partner_focal_point_last_name VARCHAR(64),
       partner_focal_point_email VARCHAR(128),
       partner_focal_point_phone VARCHAR(64)
)
